Spec_URL_navigation/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/urls.py
from django.urls import path
from app1.views import *
app_name='something'
urlpatterns=[
    path('bhoomi/',bhoomi,name='bhoomi'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='nothing'
urlpatterns=[
    path('reddy/',reddy,name='reddy'),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def bhoomi(request):
    return render(request,'bhoomi.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def reddy(request):
    return render(request,'reddy.html')

templates/bhoomi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hi reddy how are you...</h1>
        <a href="{% url 'nothing:reddy' %}"><h1>click Here for Reddy🤣🤣🤣</h1></a>
    </center>
</body>
</html>

templates/reddy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hi bhoomi how are you..?</h1>
        <a href="{% url 'something:bhoomi' %}"><h1>Click Here for Bhoomi🤷‍♂️🤷‍♂️🤷‍♂️</h1></a>
    </center>
</body>
</html>